### ISSUE TITLE
Exception setting time interval

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#1]
Hi!

Settings -> Click "Work time":

![2017-06-01_095455](https://cloud.githubusercontent.com/assets/5569346/26666506/506aa1cc-46b1-11e7-8325-01fb054c5d8c.png)

then press 'backspace':

![2017-06-01_095551](https://cloud.githubusercontent.com/assets/5569346/26666525/7065fdd2-46b1-11e7-8989-e1865453b027.png)

**Comment by floatas** [comment]
Fixed
