### ISSUE TITLE
Add a counter for number of Pomodoros made in a day

### ISSUE THREAD

**Issue by bratao** [YetAnotherPomodoroApp/YAPA-2#10]
First of all, thank you or this awesome project.

This is by far my favorite timer. Thank you for reviving the YAPA project.

One feature that I miss is the number of Pomodoros I made in day.

![image](https://user-images.githubusercontent.com/1090152/29095256-9b8df3d0-7c66-11e7-82eb-5997b73ec1ab.png)

I don´t understand the logic if this counter. It says current period, but for my case is displaying my total number of pomodoros.

Thank you

**Comment by floatas** [comment]
Hey, I'm glad you enjoy it 😃 

I have been thinking about this counter. There are several different value that can be displayed:
- pomodoros completed today (00:00 - 23:59)
- pomodoros completed this session. Restarting app would reset counter.
- pomodoro index 1, 2, 3, 4 (long break)
Best would be to have function to switch between them.

**Comment by bratao** [comment]
Awesome =)

**Comment by floatas** [comment]
Fix is in latest release
