### ISSUE TITLE
Change how many work intervals between long breaks

### ISSUE THREAD

**Issue by TheChilliPL** [YetAnotherPomodoroApp/YAPA-2#101]
I cannot see the option to change how often a long break should appear. I think it should be one of the basic configurable variables in the options.

**Comment by floatas** [comment]
Hey @TheChilliPL We have this functionality, but we don't have UI 🤔 will try to add new input in next release.

Right now you can navigate to "C:\Users\<userName>\Documents\YAPA2"
Edit settings.json file and change this number
![image](https://user-images.githubusercontent.com/7883111/197704988-7f7e0572-63b8-4935-a3cc-415844142570.png)

Right now it's 4. After 4 work pomodoros you will have long break.

**Comment by TheChilliPL** [comment]
Glad there's a way to change it!
I'll leave the issue open until the UI for it is there, though!

**Comment by floatas** [comment]
You can now specify session rounds in settings.
