### ISSUE TITLE
The app stopped working after the latest update - 2.2.0.180

### ISSUE THREAD

**Issue by DerTrolde** [YetAnotherPomodoroApp/YAPA-2#106]
Literally - when app is updated i just can not open it, not the existing, installed version, nor the new 2.2.0.180 downloaded file. After a click on the icon it just thinks for a little and nothing happens, no app running in background. The previous version still works though. Windows 11, what other info should i attach?

[log.log](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/10380339/log.log)

**Comment by jsmith0112358** [comment]
The same thing is happening to me. Did you find any solutions to this?

**Comment by DerTrolde** [comment]
The only thing that works is using the previous version - 2.2.0.179. Let's wait for the official reply :)

**Comment by floatas** [comment]
Hey @DerTrolde , thank you for reporting issue, logs that you attached were enough to identify problem. Try the latest version, and let me know how it goes.

**Comment by DerTrolde** [comment]
@floatas Thanks for the reply and surely for the fix. The next one didn't work again, but 2.0.190 shows no issue. Seems like it's good. Thank you!

**Comment by floatas** [comment]
Closing as fixed
