### ISSUE TITLE
App stops working after creating new profile - 2.2.0.180

### ISSUE THREAD

**Issue by jsmith0112358** [YetAnotherPomodoroApp/YAPA-2#107]
I am a Windows 11 user. After creating a new profile besides the default "Pomodoro", and closing the app, it disappears and won't open again. I tried running the .exe file as an administrator, to no avail. Are there any known fixes for this? Thanks!

**Comment by jsmith0112358** [comment]
After installing the updated version, the error persists. I am attaching the log file.

It reads: "FATAL Unhandled exception: Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration".

Thank you for your help.

[log.log](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/10436344/log.log)

**Comment by floatas** [comment]
Thank you for the logs ♥ please try the latest version v2.0.190.

**Comment by jsmith0112358** [comment]
It works perfectly now! Thank you so much for your help!
