### ISSUE TITLE
App crashing when i open settings 

### ISSUE THREAD

**Issue by subaangi06** [YetAnotherPomodoroApp/YAPA-2#112]
A few days i might have tried to view 100 months of pomodoro progress just to see if it would work, and every since that time, app crashes whenever I try to open settings to view the graph, is there a way to fix this

**Comment by floatas** [comment]
Hello @Harry-Potter66 
You can fix it by going to `Documents\YAPA2`  folder and edit`settings.json`
change this number:
![image](https://user-images.githubusercontent.com/7883111/232478864-8d72f185-5a30-4f0c-96f0-387d5f977d89.png)

**Comment by subaangi06** [comment]
Alright thanks alot, it was at 1000 months.. Explains the crashi
