### ISSUE TITLE
Can I export-import statistics data when I reinstall OS?

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#116]
Hi @floatas !

This is not an issue but a question.

Are there any ways not to loose my pomodoros if I reinstall YAPA?
Maybe I can grab some file and then overwrite it on new installed version?

Best regards, Gennady

**Comment by floatas** [comment]
Hey, you can create back-up, there is YAPA2 folder in my documents. 
Yapa.db - all completed pomodors
settings.json and localSettings.json - contains settings, colors, work/break times, etc

**Comment by Gennady-G** [comment]
Thank You @floatas! :)
