### ISSUE TITLE
Work time setting - 'Up arrow' decreases values?

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#21]
Hi!

![2017-09-05_224617](https://user-images.githubusercontent.com/5569346/30080531-990a248a-928c-11e7-8797-0a9cc3be1b1f.png)

YAPA 2.0.80

Usually "Up arrow" key increases value, but "down" decreases. But in Yapa it works vice versa. I often change intervals and there is a little confusion.

**Comment by floatas** [comment]
Hi, items in dropdown are in ascending order, yeah it probably makes more sense to reverse list. Then down arrow would increase.

Why do you change interval lengths? Maybe there's something that can be done in app to help ?

**Comment by floatas** [comment]
Closed automatically on commit, reopening for now.

**Comment by Gennady-G** [comment]
Hi!

> Hi, items in dropdown are in ascending order
Yes, a little non-intuitively in my opinion.. 

> Why do you change interval lengths? Maybe there's something that can be done in app to help ?
Don't think. I sometimes restart pc and then begin from last time. I also sometimes closed/reopened Yapa 1, becouse I had feeling that it begins to slow my machine after few hours (I work on low-performance laptop now). Don't know, it is only assumption.. Now I use Yapa 2 and works better.

But maybe some research about performance is good idea.. There is a small hang when interval ends. Maybe related with animation, or with sound.. Also opening menu (by right click) sometimes takes few seconds for me. 

upd.: Checked now and it works fast)

I understand that performance issues is hard to catch, and I have no bug reports now. I will pay attention and keep You posted

**Comment by floatas** [comment]
> Don't think. I sometimes restart pc and then begin from last time.

Well, I have some good news. Next release will remember and will ask if you want to continue unfinished pomodoro.  If you start pomodoro -> close app -> reopen app, it will ask if you want to continue from where you left before. This is already implemented, need to do a bit more testing.


>Also opening menu (by right click) sometimes takes few seconds for me.

I also noticed that, doesn't happen very often for me. I think it's related to dashboard.

> Maybe related with animation, or with sound

Animation do cause some performance issues, there is setting to disable animations. When animations are disabled then solid color is displayed.

Will do some performance debugging (Visual Studio has some nice tools for that) and hopefully will make next release on weekend.

**Comment by Gennady-G** [comment]
> Well, I have some good news. Next release will remember and will ask if you want to continue unfinished pomodoro. If you start pomodoro -> close app -> reopen app, it will ask if you want to continue from where you left before. This is already implemented, need to do a bit more testing.

Oh, that's great! Will it support restart, for example if I use this command to restart server:
`shutdown /r /t 30`
? 
Maybe You can add this 'autosave' to 'OnApplicationClose' event, or something similar (not sure what You use)? If so, then imho You can remove "Are You sure You want to exit and close pomodoro" confirmation window. Yapa will always know last position

> Animation do cause some performance issues, there is setting to disable animations. 

Ah Yes, I already use it. Maybe that's why I say 'it works better now' :).

> Will do some performance debugging 

I have suspicion that performance issue occurs after some hours of work. Maybe there is some small leak.. But not sure

Best regards,     
Gennady

**Comment by Gennady-G** [comment]
I can create separate bug for performance researches, if needed

**Comment by floatas** [comment]
> Oh, that's great! Will it support restart, for example if I use this command to restart server:
shutdown /r /t 30

It will support, it uses onclosing event to save. For now commented out message box with close confirmation.

I found few performance issues and fixed them. Settings should open faster and hopefully won't lag after pomodoro work end.

**Comment by floatas** [comment]
New version released, let me know if there still are performance issues.

**Comment by Gennady-G** [comment]
Cool! "Up arrows" now increase values, thank You. This bug is fixed

> It will support, it uses onclosing event to save. For now commented out message box with close confirmation.

Wow. Great! :)

> New version released, let me know if there still are performance issues.

Ok! I will look around

**Comment by floatas** [comment]
Closing bug since original issue is now fixed :) if there are other issues, please create separate issue.
