### ISSUE TITLE
If YAPA is running, interval values in settings are grayed-out

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#22]
Hi!

If YAPA is running, interval values in settings are grayed-out. I was able to change these values "on-the-fly" before. Is this option disabled since YAPA 2.0.98?

![2017-09-11_160306](https://user-images.githubusercontent.com/5569346/30373887-8e81bd5c-988b-11e7-8063-4b12fe4741ae.png)

**Comment by floatas** [comment]
Hi,
Yes in previous versions you could change these values when pomodoro was running, is it something you do often ? change intervals while pomodoro is running ?

**Comment by Gennady-G** [comment]
Hi!
Yes, sometimes I add/substract 5-10 minutes to Yapa interval. It occurs
because sometimes I don't stop and keep working on "Pause time". I can make
break in the middle of next pomodoro, for example.. And later I can
substract "used time"..

For example if work interval is 25min I can work 28, and then next pomodoro
would be 22min.

I now it is wrong and 'non-GTD style', but I do it often :) My pomodoros
are not 'static', they change a little..

**Comment by floatas** [comment]
I will try to make smaller release on sunday, will enable work\break time edit on pause.

**Comment by Gennady-G** [comment]
Thank You!)

**Comment by Gennady-G** [comment]
All work like a charm now, thank You!

**Comment by floatas** [comment]
Fixed.
