### ISSUE TITLE
Bring to front YAPA counter on Balloon Tip click

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#23]
Hi!

Can You show YAPA counter if balloon tip is clicked? Or can You please add option, something like "Show Yapa on balloon click"? So this change will not affect other users..

**Comment by floatas** [comment]
Added option to bring to front.

**Comment by Gennady-G** [comment]
Thank You floatas! Will download/rebuild solution today and close

**Comment by floatas** [comment]
I will try to make new release this week.

There is no need to build manually, on every new commit to repository new build is made.
Fallow these instructions https://github.com/YetAnotherPomodoroApp/YAPA-2#nightly-builds 
and you will auto update to these changes.

**Comment by Gennady-G** [comment]
Thank You!
