### ISSUE TITLE
"Dismiss break" button?

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#24]
When Work is ended, there is empty place and "Start" button. Don't now how other use YAPA, but I sometimes cancel break and continue with next pomodoro. So I click Start->Stop->Start and continue. Maybe You can add something like "Dismiss", or "Continue work" button. Here we have free space (or it looks like free space):

![2017-09-13_113701](https://user-images.githubusercontent.com/5569346/30374393-80fbc6d0-988d-11e7-992a-6e1424df061c.png)

**Comment by floatas** [comment]
Added button to Skip break. So after work ends you will need to press Skip, then Start (to start next work pomodoro).

**Comment by Gennady-G** [comment]
Thank You, will test and give feedback

**Comment by floatas** [comment]
Fixed.
