### ISSUE TITLE
Exception clicking "System Tray" Plugin

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#25]
Hi!

If I stop YAPA, go to setings -> expand "Plugins" -> System Tray, Then I get exception:

![2017-09-15_134428](https://user-images.githubusercontent.com/5569346/30485060-ed292764-9a34-11e7-8d3a-c3fa99ea604d.png)

> Problem signature:
>   Problem Event Name:	CLR20r3
>   Problem Signature 01:	YAPA.exe
>   Problem Signature 02:	2.0.98.0
>   Problem Signature 03:	59b5774f
>   Problem Signature 04:	YAPA
>   Problem Signature 05:	2.0.98.0
>   Problem Signature 06:	59b5774f
>   Problem Signature 07:	4e
>   Problem Signature 08:	0
>   Problem Signature 09:	GQ4LHWPDDL0MLXLXMR0BYB3HLMJR32NC
>   OS Version:	6.3.9600.2.0.0.272.7
>   Locale ID:	1049
>   Additional Information 1:	5861
>   Additional Information 2:	5861822e1919d7c014bbb064c64908b2
>   Additional Information 3:	5f25
>   Additional Information 4:	5f2531ae070278f893fa99352dadd49e
> 
> Read our privacy statement online:
>   http://go.microsoft.com/fwlink/?linkid=280262
> 
> If the online privacy statement is not available, please read our privacy statement offline:
>   C:\Windows\system32\en-US\erofflps.txt
>

**Comment by floatas** [comment]
Hi, can you navigate to %localappdata%\YAPA2\Logs 
Zip log files and attach them here

**Comment by Gennady-G** [comment]
Greetings!

Sure! Reproduced and attached logs
[Logs.zip](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/1307522/Logs.zip)

**Comment by Gennady-G** [comment]
Hmm..
Maybe it is my error.
I start YAPAwith shortcut:

and there is old directory in "Start in" option:
![2017-09-15_221247](https://user-images.githubusercontent.com/5569346/30499444-3924d324-9a63-11e7-9c53-ca87f8d2a184.png)

So maybe it is not a bug but my inattention.

But if I change folder to "app-2.0.98" I still get exception oO

**Comment by floatas** [comment]
hmm, few things that you can try. 
1. Close application
2. Move this file to other location"Documents\YAPA2\settings.json"
3. Open app and try to reproduce issue
If there are no issue, can you attach this file ?

If that doesn't help, you can try to reinstall application (settings will remain).

**Comment by Gennady-G** [comment]
Hi!

 

Have tried, same result. Ok, I’ll remove and completely reinstall application

**Comment by Gennady-G** [comment]
Uninstalled, deleted folder "C:\Users\Administrator\AppData\Local\YAPA2" and installed again.
Interesting, same result. Attached Logs here
[Logs.zip](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/1308379/Logs.zip)

I had YAPA1 installed before (I think I compiled from sources,don't remeber..)
[2_eventvwr_events.zip](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/1308380/2_eventvwr_events.zip)

**Comment by floatas** [comment]
Application fails because it tries to load "Xceed.Wpf.Toolkit.AeroLite" but this dll doesn't exist. This file is not present on my machine and I have zero issues. 

Do you remember when did this issue started ? Have you changed any specific settings in application ? Or in Windows ? have you changed windows theme, enabled aero or something like that ?

**Comment by Gennady-G** [comment]
Wow.. 

> This file is not present on my machine and I have zero issues.
Very strange..

> Do you remember when did this issue started ? Have you changed any specific settings in application ? Or in Windows ? have you changed windows theme, enabled aero or something like that ?
I got when tried to turn "minimize to tray" option, for the last version..

Yes I made changes and played with settings, but there were too much changes( For example I've changed Office 2016 to 2013, turned On/Off motivational theme, installed GoldenDict dictionary (based on Qt C++ library, so I think it installed something..), etc. 

My OS is 'Windows Server 2012'
I installed YAPA downloading latest *.exe release 

Interesting that I can reproduce it on another Win Server 2012 (virtual) machine, just tried. If I click "Debug program" I see this string in VS debugger:

> Autofac.Core.DependencyResolutionException was unhandled
> Message: An unhandled exception of type 'Autofac.Core.DependencyResolutionException' occurred in PresentationFramework.dll
> Additional information: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = MinimizeToTraySettingWindow (ReflectionActivator), Services = [YAPA.Plugins.MinimizeToTray.MinimizeToTraySettingWindow], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope
>

**Comment by Gennady-G** [comment]
Wanted to test on empty Win Server 2012 **R2** (have machines with server OS only), but got warning

![2017-09-16_224340](https://user-images.githubusercontent.com/5569346/30515460-b513a366-9b30-11e7-924d-6511cc2a687b.png)

YAPA needs .NET 4.6.1, wow..

**Comment by floatas** [comment]
I tried on windows server 2012, but no issues.
You can try latest version, maybe it will help. I found that Xceed.Wpf.Toolkit repository has this bug reported, but no fix.

**Comment by Gennady-G** [comment]
> I tried on windows server 2012, but no issues.
Maybe You have latest updates on Your 2012 (I usually turn off auto updates on servers). This dll could be injected into another and come with update..

> You can try latest version, maybe it will help. 
Yes, great! All works in latest release 2.0.107. Wow, nice panels with colors)

**Comment by floatas** [comment]
Fixed.
