### ISSUE TITLE
Feature request: remove start/stop/etc buttons

### ISSUE THREAD

**Issue by grokky1** [YetAnotherPomodoroApp/YAPA-2#27]
The start/stop/minimize/close/etc buttons to the right of the clock take too much space...

Would be nice to:
- left click on the clock itself: start/stop
- right click: something else
- middle click: something else

Could be an optional setting.

This would be great to keep the app small and neat.

**Comment by Gennady-G** [comment]
> The start/stop/minimize/close/etc buttons to the right of the clock take too much space...

oO

> Could be an optional setting.

It should be plugin, because new functions should not break existing functionality

> •	left click on the clock itself: start/stop

Also think this could be very interesting. Maybe if click was over "YAPA 2.0" - use drag-n-drop, but click on the clock starts/pause interval. Even more - one click pauses/resumes, but double click - "skip and start next interval"

**Comment by floatas** [comment]
minimize/close are only visible when mouse is over application.
Setting can be added to make same with buttons. Only visible when mouse is over application.

**Comment by Gennady-G** [comment]
> Maybe if click was over "YAPA 2.0" - use drag-n-drop, but click on the clock starts/pause interval. Even more - one click pauses/resumes, but double click - "skip and start next interval"

Hi **floatas**!

What do You think about this feature? If You don't mind I can create different request for it

**Comment by floatas** [comment]
> Maybe if click was over "YAPA 2.0" - use drag-n-drop, but click on the clock starts/pause interval. Even more - one click pauses/resumes, but double click - "skip and start next interval"

I'm not 100% sure about this one, "YAPA 2.0" area is really small and it doesn't have visible boundaries. After this change there might be a lot of accidental clicks to wrong areas.

**Comment by Gennady-G** [comment]
Mm.. I understand

Maybe keep drag-n-drop as it is and add "pause/resume on double-click" plugin?

**Comment by grokky1** [comment]
For me it is actually big, because I increased the size, so it is easily visible. I guess other users may keep it normal size.

**Comment by floatas** [comment]
Added option to hide buttons.
