### ISSUE TITLE
Feature request: option to not update the seconds

### ISSUE THREAD

**Issue by grokky1** [YetAnotherPomodoroApp/YAPA-2#28]
I use a analog timer, so no seconds flashing by. I find the digital timers distracting because of the changing seconds... even causes anxiety when working on something deep 😆 .

Would be nice to NOT show counting seconds. Just update the timer each minute, but don't update the seconds.

Could be an option in the settings.

**Comment by floatas** [comment]
Will be in next release.  Also available in nightly builds, if you want to test sooner.

![onlyminutes](https://user-images.githubusercontent.com/7883111/30757422-5df69a9c-9fd7-11e7-93dc-36f6fbed0812.PNG)

**Comment by grokky1** [comment]
Thanks for this!

**Comment by Gennady-G** [comment]
Strange but this setting is not always saved for me.
If I go Menu -> tick "hide seconds", all is ok. But later after few restarts is continue to show seconds (when "Hide seconds" checkbox is checked). 

Don't You have this issue?

Tried to dowload *.exe and reinstall, does not help. Maybe I need to completely remove all files in 

> C:\Users\Administrator\AppData\Local\YAPA2

and make clean install?

**Comment by floatas** [comment]
I can reproduce this issue. This is bug, will fix it for next release.

**Comment by floatas** [comment]
Bug fixed.
