### ISSUE TITLE
Show in tray option

### ISSUE THREAD

**Issue by grokky1** [YetAnotherPomodoroApp/YAPA-2#29]
Doesn't work for me. When enabled, nothing is in the tray.

But if I minimize, then it shows in the tray. Is this the expected behavior, because it's a little strange for Windows...

(I would expect, that if not shown in the taskbar, and shown in the tray, that it should show there all the time, even if not minimised).

**Comment by floatas** [comment]
Make sense to behave like this, no one was bothered by this so far. Will be fixed in next release.

**Comment by floatas** [comment]
Fixed.
