### ISSUE TITLE
Wrong values in notification bar

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#3]
Hi!

I set Work interval to 50 minites:
![2017-06-01_100452](https://cloud.githubusercontent.com/assets/5569346/26666630/0a4dc600-46b2-11e7-81a7-c537c9eaa7b5.png)

I have "Minimize to tray" enabled,  "Show in taskbar" disabled, and "Count backwards" enabled.

Started counter. It should show '49'. But when minimized it shows '29':
![2017-05-31_132653](https://cloud.githubusercontent.com/assets/5569346/26666658/29202e42-46b2-11e7-9353-a61cdc81d944.png)

**Comment by floatas** [comment]
Fixed
