### ISSUE TITLE
Feature request: functionality to deal with black/white backgrounds

### ISSUE THREAD

**Issue by grokky1** [YetAnotherPomodoroApp/YAPA-2#30]
Are any of you using this on a multi-monitor setup? I do, so I put the timer on the second screen. Problem is that alot fo the time it's empty, and if the timer text is black then I can't see it.

I could use the white text option, but that's no good as it disappears when a window is open (most apps are white background).

What would be a good solution?

Some possibilities:
- white/black/other background on hover
- option to set text color (I'd choose something that shows on both black and white backgrounds)
- change text color on hover
- live with it 😆

**Comment by Gennady-G** [comment]
Had same problem. Changed to white and set opacity to max. Not ideal, but now more visible on black and white:

![2017-09-23_200711](https://user-images.githubusercontent.com/5569346/30775375-efeb7dfa-a09a-11e7-9aa5-2738a3158cd5.png)

**Comment by grokky1** [comment]
@Gennady-G LOL that's exactly what I did too. 👍 

It's a good workaround for now, but it would be awesome if there was a better way.

**Comment by floatas** [comment]
> option to set text color
This could be implemented. Two color pickers one for text, other for shadow.

**Comment by floatas** [comment]
:see_no_evil:
![image](https://user-images.githubusercontent.com/7883111/30783352-5149c3ea-a14a-11e7-887e-054ebdbfc30f.png)

**Comment by grokky1** [comment]
Thanks for this! closing...
