### ISSUE TITLE
YAPA slows down machine

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#32]
Hi!

It **really** slows down my laptop. But I need few hours to see it (3-5 intervals for 50 minutes). Think there is a leak, but not sure how to catch it. Maybe I need to install profiler or use tools from [Sysinternals](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer)? Do You have any idea?

**Comment by floatas** [comment]
What do you mean by slow down ? Task manager starts to show high CPU\RAM usage ?

**Comment by floatas** [comment]
In order to catch it, you can open Task Manager find YAPA2 process and create dump file (right click on process). Zip it and attach here.

**Comment by Gennady-G** [comment]
> What do you mean by slow down ? 
"Slow down" - it slowly switches between application windows, hangs. If I close YAPA it stops hanging. It occurs after few hours of application work

> Task manager starts to show high CPU\RAM usage ?
my RAM usage is high all the time.. I'm not sure it is related with RAM, maybe HDD?

Will try to create dump net time

**Comment by Gennady-G** [comment]
Yapa with new colors looks great imho)

![2017-10-03_223808](https://user-images.githubusercontent.com/5569346/31145280-fcd3b796-a88b-11e7-83f4-3e1a4f769b62.png)

Also right click works much faster. Have you made some improvements in this area?
I cannot reproduce bug when my pc hangs, so let's close it. And if I have more data or dump I'll reopen/recreate it.

Best regards,     
Gennady

**Comment by Gennady-G** [comment]
Think I catched something.

After few hours of work my PC hanged (mouse moved slowly, youtube hanged, etc). I launced process explorer. Please note "Page Faults" columns(9th from the left). This number (149'829 was permanently growing). Also other numbers I think are too big ("Working set" is slightly less than chrome has. But chrome has ~25 high-loaded tabs and open DevTools, and Yapa is counter. Why too big values?..)

![2017-10-25_170354](https://user-images.githubusercontent.com/5569346/32062612-a841f734-ba7d-11e7-99ef-4917f56fd252.png)

I created dump, made screenshots and then closed Yapa. After this all started to work very fast again. 

What I can say is that Yapa was opened (not minimized). And I also suppose that this behaviour starts after few hours of work. Maybe there is a leak in .NET, or a conflict with another program..

YAPA.exe.txt - Process Explorer log (You need https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer to import it)
2017-10-25_170504.zip - screenshots

The whole dump is too big. Do You nedd it? I will upload later if needed

I can attach logs from here:
"C:\Documents and Settings\Administrator\AppData\Local\Application Data\Microsoft\Windows\WER\ReportArchive"
[ReportArchive.zip](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/1419076/ReportArchive.zip)

[2017-10-25_170504.zip](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/1419059/2017-10-25_170504.zip)

**Comment by Gennady-G** [comment]
dump:
https://mega.nz/#!WkNmCbJa!gDXtsihG6A8tLUdnOuG_DwkkwvFkAKQSbXGj1ChZyWo

**Comment by floatas** [comment]
Reopening for visibility.
