### ISSUE TITLE
"Volume" setting

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#33]
Hi!

"Volume setting" and "disable sounds" should be on 'Sound' tab, imho?..

![2017-10-05_142217](https://user-images.githubusercontent.com/5569346/31225020-dde98394-a9d8-11e7-94c7-fe31ed3a39be.png)

**Comment by floatas** [comment]
Yes, it would make more sense to put these settings in "Sound" tab. Originally General tab supposed to contain global settings, settings that are useful for plugins. "Sound" is just another plugin, it's special because it can't be disabled.

**Comment by floatas** [comment]
Fixed.
