### ISSUE TITLE
"Skip" button improvements

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#34]
Hi **floatas**!

Is it hard to start work interval immediately, if "Skip" is pressed?.. 
And can You also add "Skip" to this menu?

![2017-10-17_115128](https://user-images.githubusercontent.com/5569346/31655594-0441500a-b332-11e7-9f64-e3337618de28.png)

**Comment by floatas** [comment]
Fixed.

**Comment by Gennady-G** [comment]
For me it's **very** useful! Thank You.
Also - "Unclickable mode" looks very cool. Great release.

**Comment by fufirel** [comment]
I'm sorry... How can I import the extension codes?

**Comment by floatas** [comment]
@fufirel  what are you trying to import? What extensions are you talking about?

**Comment by fufirel** [comment]
@floatas this one: [https://github.com/YetAnotherPomodoroApp/YAPA-2/commit/7bb9aceb74a1897b96bc2f80c2dcca93255231c2](url)
Thank you very much for the creating and the support, I live the software...!

**Comment by floatas** [comment]
I will take a look. Might be that we need to make new release.

**Comment by floatas** [comment]
@fufirel new YAPA version was released, it should update automatically to 2.0.142, or you can download the full installer.
