### ISSUE TITLE
Updated RAM 8gb -> 16gb, cannot reinstall Yapa

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#38]
Hi @floatas !

Do I need to download solution and recompile it in this case?

![2018-03-09_141647](https://user-images.githubusercontent.com/5569346/37202761-e205ad0e-23a4-11e8-9353-3f0e2dfdf3ed.png)

Best regards, 
Gennady

**Comment by floatas** [comment]
Hello Genady, 
Can you provide a bit more information ? How much memory app is using ? Which version are you using ? Crashes instantly or after some time ?

**Comment by Gennady-G** [comment]
On YAPA application start.
I downloaded project *.zip(YAPA 2.0.133) and tried to rebuild on my pc, but no luck. Same error when I launch 

> \YAPA-2-master\Build\Releases\Setup.exe

**Comment by Gennady-G** [comment]
What should I do to make 'full reinstall' of YAPA application? Maybe this would help

**Comment by Gennady-G** [comment]
![2018-03-09_203656](https://user-images.githubusercontent.com/5569346/37218375-abdadc7e-23d9-11e8-81bd-4524ebae724d.png)

**Comment by Gennady-G** [comment]
Resolved. There were problems with setting files, imho. 
- Uninstalled YAPA
- Reemoved folder manually:

> C:\Users\Administrator\Documents\YAPA2

- Reinstalled.

**Comment by Gennady-G** [comment]
Oh @floatas , can You please add checkbox 'disable updates'? :)

![2018-03-13_114433](https://user-images.githubusercontent.com/5569346/37340373-57cc2a1a-26d7-11e8-9379-9fec27a45c27.png)

**Comment by floatas** [comment]
Does this file exist on your machine "C:\Users\<UserName>\Documents\YAPA2\Snapshot.json" ? if so can you upload it ?

**Comment by Gennady-G** [comment]
Yes it exists and is empty. Attached the whole folder
[YAPA2.zip](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/1810139/YAPA2.zip)

**Comment by Gennady-G** [comment]
I was wrong, it **looks** empty but it has 240 bytes

**Comment by floatas** [comment]
Does your pc crash a lot ? Are you killing YAPA from task manager ?
You can open that file with notepad++ and it will show that there are a lot of NULL. For some reason out of nowhere this files started to get corrupted in your machine. 

What happens:
1. Create file with buffer (240 chars long)
2. ???
3. File is left with NULLS, because something happened (crash ?) and content wasn't written. 

If this happens consistently, I would recommend to buy a lottery ticket :)

I will look into it. Disabling updates won't solve this issue.

**Comment by Gennady-G** [comment]
Ahhah)) Thank You for recommendation :-)

I always use Your app in my work, and after update it does not launch(link to Yapa is in shell:startup). Or I can try to launch it manually, it crashes in both cases.

I've rebuilt Your solution and reinstalled. Maybe this broken Your upgrade process?
Maybe You need to add some additional checks for configuration files, for example

`
try {
  // Load settings.json, snapshot.json or not sure what do You do there

  // ..some shit happened here..
} 
catch(Exception ex) {
  // Recreate settings.json etc. from scratch
}
`
Maybe this will resolve?

> For some reason out of nowhere this files started to get corrupted in your machine.

That's true, bugs love my machine)

**Comment by floatas** [comment]
This should be fixed in release and pre-release builds.  Try to update and see if this happens again.

**Comment by Gennady-G** [comment]
YAPA 2.0.138? I cannot install it

I download Setup.exe, unblock it
![unblock](https://user-images.githubusercontent.com/5569346/37449627-6801938e-2844-11e8-90eb-ade3faad13ef.png)

Then launch
![2018-03-15_112950](https://user-images.githubusercontent.com/5569346/37449644-70e3d5de-2844-11e8-98a6-8d46b99e3048.png)

![2018-03-15_113555](https://user-images.githubusercontent.com/5569346/37449781-0a469c16-2845-11e8-978e-4b0ee89e62a5.png)

I'll add few latest events from **eventvwr.exe**
[yapa-events.zip](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/1814360/yapa-events.zip)
[Report.zip](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/1814361/Report.zip)

And also AppCrash report. not sure if You need it. I think something related with configuration files, maybe some (de)serialization function fails?..
Or something with .NET versions. don't know
> C:\Users\Administrator\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_YAPA.exe_1069cba5ad3c192533bbf5dbb41cba64af8248c5_a4bdc2b0_1374d03c\Report.wer
[Report.zip](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/1814362/Report.zip)
[yapa-events.zip](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/1814363/yapa-events.zip)

**Comment by Gennady-G** [comment]
I'll clone sources in the evening and try to find string where it occurs

**Comment by floatas** [comment]
Your settings.json is also corrupted. Try to remove it, then it will work. Will add more try catches. How does this happens for you....

**Comment by Gennady-G** [comment]
Deleted. It's installed and is working now, thank You!

Yes, settings.json contains nulls too, imho. 588 bytes..

Will close now, let's check again with next update :)
Thank You!
