### ISSUE TITLE
Start/Close/Minimize buttons not visible on white background

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#4]
Hi!
Subj. 

Here is example:

![2017-05-31_131835](https://cloud.githubusercontent.com/assets/5569346/26666873/54906474-46b3-11e7-94f3-b221d773c81c.png)

Maybe we can make buttons color Gray, so they would be visible everywhere?..

**Comment by floatas** [comment]
Changed white to light gray

**Comment by floatas** [comment]
Some changes were done to theme, when mouse is over application Min\Close buttons are shown.
