### ISSUE TITLE
NuGet packages should not be in git repo

### ISSUE THREAD

**Issue by AlexP11223** [YetAnotherPomodoroApp/YAPA-2#45]
Why do you store some packages in the git repo? Usually they should not be here, NuGet restores them automatically.

**Comment by swtch1** [comment]
What if the package is removed from NuGet?

**Comment by AlexP11223** [comment]
They cannot be deleted except some cases like malicious packages, etc. https://docs.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages

**Comment by floatas** [comment]
I agree that most of the packages should be not in code/git. Probably they were included by accident, while fixing them I will try to update all references.

**Comment by floatas** [comment]
Removed nuget packages from source, and updated gitignore. 
There is `Libraries` folder with dll that is not from nuget.
