### ISSUE TITLE
Minimize/Close buttons are not clickable sometimes

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#5]
Hi!

Here are my Theme settings:

![2017-06-01_101742](https://cloud.githubusercontent.com/assets/5569346/26666948/bfd20044-46b3-11e7-965f-ce157bce40a2.png)

and sometimes I need to quickly minimize Yapa, but minimize/close buttons are not visible at all:

![2017-06-01_101924](https://cloud.githubusercontent.com/assets/5569346/26666977/f29c561e-46b3-11e7-9574-99618dabb46a.png)

What I noticed is: if I move mouse over "Pause/Stop" buttons - minimize/close appear. But - if I move mouse from top down, there is no buttons:
![2017-06-01_102404](https://cloud.githubusercontent.com/assets/5569346/26667175/eebe2dc8-46b4-11e7-9c3a-3a3377aa25d2.png)

(I need to hover over "pause/stop", and they appear)

**Comment by floatas** [comment]
This happens because elements are transparent, and they become visible only when mouse is over. Changed transparency to lowest possible but larger than zero, should fix this issue.

**Comment by Gennady-G** [comment]
> elements are transparent, and they become visible only when mouse is over. 

"Minimize/Close" buttons become visible only when I hover mouse over "Stop" button

p.s.: why are "minimize/close" buttons transparent? is it necessary?

**Comment by Gennady-G** [comment]
You can make make YAPA larger and ensure. Here "minimize" button is not visible:

![2017-06-02_141909](https://cloud.githubusercontent.com/assets/5569346/26721970/119a61f0-479f-11e7-8247-24ef6233eef9.png)

Red arrow shows direction how I move my mouse

**Comment by floatas** [comment]
Are you using 2.0.41 version ? I will do some work to make update'ing faster.
I have changed layout a bit. 
It's transparent to look nice with transparent timer.

**Comment by Gennady-G** [comment]
> Are you using 2.0.41 version ? I

Emm.. not sure, I don't see these changes, . As I've understand it updates automatically..
I'll download actual version from repo

**Comment by floatas** [comment]
Version is shown in settings (bottom left corner).
Currently when you start app it will download all updates, when you next time start application it will start that new version. 

I will work to improve update process.

**Comment by Gennady-G** [comment]
> Version is shown in settings (bottom left corner).
Aaah.. Yes, 2.0.41.

I place "YAPA 2.lnk" shortcut to _shell:startup_ folder. Maybe it was a problem (sometimes I see YAPA gives exception on startup, maybe because internet connection is not ready yet).

"Minimize/Close" buttons are now clickable. Much better, thank You!

**Comment by floatas** [comment]
Theme layout updated, application previously was fully transparent, mouse clicks went through empty spaces. Transparency was set to lowest possible value, app looks transparent but mouse hit test works.
