### ISSUE TITLE
Cannot find a window after additional monitor plug in \ plug out

### ISSUE THREAD

**Issue by kra5h** [YetAnotherPomodoroApp/YAPA-2#52]
Win 7, plugged in an additional monitor, moved the app to the second screen.
After plugging the monitor off, cannot find the window. Plugging in does not work.

**Comment by floatas** [comment]
As a workaround you can navigate to Documents\YAPA2  and edit localSettings.json file by removing SaveApplicationPositionOnScreen object.

**Comment by bertster61** [comment]
I am having a similar problem after using a monitor. Cannot find the window but the program runs just fine in the taskbar. Tried deleting local settings, before downloading a json editor, but now there's nothing in the file to edit and the problem still persists. Any help would be appreciated.

**Comment by bertster61** [comment]
> As a workaround you can navigate to Documents\YAPA2 and edit localSettings.json file by removing SaveApplicationPositionOnScreen object.
> You can remove localSettings.json file, it will be created when you restart app.

I am having a similar problem after using a monitor. Cannot find the window but the program runs just fine in the taskbar. Tried deleting local settings, before downloading a json editor, but now there's nothing in the file to edit and the problem still persists. Any help would be appreciated.

**Comment by Silverlinin** [comment]
ditto, concerned that I may have to keep searching for another app that is updated..miss this one

**Comment by floatas** [comment]
Related to #81 , will try to fix for next release.

**Comment by floatas** [comment]
Did some improvements related to window position, there were some problems related to DPI settings.
