### ISSUE TITLE
Please rename setup.exe

### ISSUE THREAD

**Issue by jlnprssnr** [YetAnotherPomodoroApp/YAPA-2#58]
Windows 10 will always run exes named _setup_ as admin, which results in an error. Renaming the exe to something else (YAPA2 for example) works.

https://superuser.com/questions/171917/force-a-program-to-run-without-administrator-privileges-or-uac/1398329#1398329

**Comment by floatas** [comment]
Thank you for creating an issue. Just a reminder for myself: update build scripts to rename squirell generated  files.

**Comment by floatas** [comment]
Updated build scripts, future releases will have different exe name
