### ISSUE TITLE
Wrong values in Break Time

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#6]
Hi!

Here are my settings:
![2017-06-01_134108](https://cloud.githubusercontent.com/assets/5569346/26674146/6a800cc2-46d0-11e7-80f6-cd18e69b08f0.png)

and 'Break time' should be '4' but it is '33'.

**Comment by Gennady-G** [comment]
Break time looks Ok but now same bug with work interval. Maybe You cannot reproduce it because it works ok on first iteration.. 
Here my settings are : '50' mins, but it starts from '38' mins

![2017-06-06_161827](https://cloud.githubusercontent.com/assets/5569346/26828782/f3a8d2b6-4ad3-11e7-887a-c2e95387c574.png)

Do You stop counter, when values are 00:00 and "Start" wasn't pressed?

**Comment by floatas** [comment]
Issues with break time fixed.
