### ISSUE TITLE
Windows 10 issue

### ISSUE THREAD

**Issue by jlbradley1844** [YetAnotherPomodoroApp/YAPA-2#61]
Strarting YAPA today, I started it, but the counter did not appear anywhere on the window. I can see it only if I hover over YAPA on the task bar.

This happened repeatedly. An hour later, just toying around with it, it -did- start up fine. So no idea what's up with that.

**Comment by arigatory** [comment]
I have the same problem. Have you found the solution?

**Comment by Luca-Bo** [comment]
Same issue. I have solved with deleting the files .json under documents\YAPA2.

**Comment by floatas** [comment]
Did some improvements related to window position, there were some problems related to DPI settings.
