### ISSUE TITLE
Automatically start next work session after break

### ISSUE THREAD

**Issue by nbacon0** [YetAnotherPomodoroApp/YAPA-2#62]
Currently there is only an option to auto start the next break after a work interval: it would be quite nice if there was also an option to completely automate this so that the next work interval starts after a break.

Example:

Current behavior: Work Interval --Autostart--> Break --Manual Start--> Work Interval

Desired Behavior: Work Interval --Autostart--> Break --Autostart--> Work Interval -->Autostart--> Break --Autostart--> Rinse and repeat

Obviously having a beep or indicator when Autostart kicks into a Work Interval would be the ideal.

**Comment by DerTrolde** [comment]
If the feature is implemented, the issue can now be closed, right?

**Comment by floatas** [comment]
Not yet, I haven't merged the pull request.

**Comment by floatas** [comment]
Released

**Comment by DerTrolde** [comment]
@floatas Thanks for keeping this up :)
