### ISSUE TITLE
Cannot cancel "Break Time" and start new working interval

### ISSUE THREAD

**Issue by Gennady-G** [YetAnotherPomodoroApp/YAPA-2#7]
Subj.

When in "Break Time" - can only click Start, or Pause/Stop. It only restarts Break Time from the beginning, but I need to have ability to Discard this break and start new Work Interval.

**Comment by floatas** [comment]
I think this will be connected to #6, made small fix for it. Can't reproduce it.

**Comment by Gennady-G** [comment]
>> Can't reproduce it.
Thank You! Ok, I'll test

**Comment by Gennady-G** [comment]
Yes, it is fixed. Now as I understand - I can't pause break interval?.. But as for me I don't need this function, so Ok, thank You!

**Comment by floatas** [comment]
Yes, pause intervals can't be paused.
