### ISSUE TITLE
Using more than 99 minutes timer don't show correctly

### ISSUE THREAD

**Issue by fufirel** [YetAnotherPomodoroApp/YAPA-2#79]
Actually... I use a 125/25/75 timer...
100 minutes don't show correctly... 125 become 25 and so on... Is there anything I can do to fix that?
Thank you...!

**Comment by floatas** [comment]
Never actually thought someone would use that large interval. I will take a look, this should be a small fix.

**Comment by floatas** [comment]
One thing led to another, and now we have custom font support, plus three-digit numbers are supported.

![image](https://user-images.githubusercontent.com/7883111/150683741-ce06ba68-118a-47f7-ab32-b21b96f8521a.png)

![image](https://user-images.githubusercontent.com/7883111/150683759-af50fd60-0c7a-4b80-b6d7-3861aee2c0eb.png)
