### ISSUE TITLE
Add option to repeat or change stop sound

### ISSUE THREAD

**Issue by ihodev** [YetAnotherPomodoroApp/YAPA-2#8]
This will be especially useful if you minimize YAPA to tray and work in the fullscreen mode.

**Comment by floatas** [comment]
There is option to add "Break song" which will be played on break and it has repeat option.
 Balloon tooltips might be useful in this scenario.

**Comment by floatas** [comment]
Balloon tips will be available in next version. 
They are currently available in [Nightly builds](https://github.com/YetAnotherPomodoroApp/YAPA-2#nightly-builds), if you want to try it.

**Comment by floatas** [comment]
Implemented, balloon tips are in latest release.

**Comment by johnyoonh** [comment]
The repeat doesn't seem to work. Tested on commit dcb8fc
