### ISSUE TITLE
Timer window has disappeared 

### ISSUE THREAD

**Issue by Beth5322** [YetAnotherPomodoroApp/YAPA-2#81]
The application will open, settings can be accessed through the taskbar icon and a timer can be started but the clock/timer window cannot be seen

**Comment by floatas** [comment]
Hello, go to My Documents\YAPA2 and delete settings.json file, then restart application.

I will look at how to fix this bug. Thank you for reporting.

**Comment by Beth5322** [comment]
> Hello, go to My Documents\YAPA2 and delete settings.json file, then restart application.
> 
> I will look at how to fix this bug. Thank you for reporting.

Hello, that worked. Thank you so much for the prompt reply.

**Comment by floatas** [comment]
Did some improvements related to window position, there were some problems related to DPI settings.
