### ISSUE TITLE
Can't minimize to tray

### ISSUE THREAD

**Issue by Pramuspl** [YetAnotherPomodoroApp/YAPA-2#86]
I enabled the tray plugin but I can't seem to find a way to minimize it to tray. Regular minimize sends the app to taskbar. Is it broken?

**Comment by floatas** [comment]
Hey @Pramuspl 
can you check if you have this option checked? 
![image](https://user-images.githubusercontent.com/7883111/151562210-57166634-98ae-4659-b3b4-786688ab17b5.png)

**Comment by floatas** [comment]
Made small change: when "System tray" plugin is enabled the first time, "Minimize to tray" will be checked by default.

Feel free to create a new issue if you still have any issues with this functionality.
