### ISSUE TITLE
Add option to change the color of the time when YAPA is minimized to tray

### ISSUE THREAD

**Issue by ihodev** [YetAnotherPomodoroApp/YAPA-2#9]

**Comment by floatas** [comment]
Should be in 2.0.53 version.

**Comment by ihodev** [comment]
@floatas I think something goes wrong after update :( Tested on Windows 7 & 10, should I remove some old stuff?

```
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	YAPA.exe
  Problem Signature 02:	2.0.53.0
  Problem Signature 03:	59743970
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.6.1099.0
  Problem Signature 06:	58d872b6
  Problem Signature 07:	44e3
  Problem Signature 08:	0
  Problem Signature 09:	5O2O3I2ORVH4ZJ0NRQ1HQUEQ4B3YAU4U
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

**Comment by ihodev** [comment]
[WERBBB8.tmp.appcompat.txt](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/1169458/WERBBB8.tmp.appcompat.txt)

[WERB004.tmp.WERInternalMetadata.xml.txt](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/1169457/WERB004.tmp.WERInternalMetadata.xml.txt)
[WERBD2F.tmp.mdmp.txt](https://github.com/YetAnotherPomodoroApp/YAPA-2/files/1169459/WERBD2F.tmp.mdmp.txt)

**Comment by floatas** [comment]
Build failed, but was marked as successful by build server... I will set up nightly builds to avoid this in the future. Thank you for quick feedback.

Go to installation dir: %localappdata% and remove app-2.0.53\Themes\Motivational.dll

App should start. Removed 2.0.53 version from server, shouldn't update again.
