### ISSUE TITLE
Wrong date on "Last 60 days" chart

### ISSUE THREAD

**Issue by mksmpc** [YetAnotherPomodoroApp/YAPA-2#99]
**Issue location:** Settings - Dashboard

**Problem:**
When I choose `Number of months == 1` the **Last 60 days** chart displays the incorrect date (in the past):

![image](https://user-images.githubusercontent.com/10189223/179026390-24399d4d-f1f7-4bbf-844e-d67318253ed3.png)

---

If I select 2 or more months, the dates are displayed correctly:

![image](https://user-images.githubusercontent.com/10189223/179028232-8d3e6544-ee4c-4491-bc68-73818d090838.png)

**Comment by floatas** [comment]
Fix released.
